### ISSUE TITLE
模仿homefragment 写了一个界面，显示空白

### ISSUE THREAD

**Issue by jackandroid2016** [wushaoge/WsgMvvm#1]
数据返回正常
![图片](https://user-images.githubusercontent.com/19246186/94994994-bfd87280-05cd-11eb-8abf-3e05bafa03bc.png)
也走到这里边了，应该显示空布局的，然而并没有显示

**Comment by wushaoge** [comment]
loading是true的话&nbsp; 用getMain的网络请求



---原始邮件---
发件人: "风..."<notifications@github.com&gt;
发送时间: 2020年10月3日(周六) 晚上11:12
收件人: "wushaoge/WsgMvvm"<WsgMvvm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [wushaoge/WsgMvvm] 模仿homefragment 写了一个界面，显示空白 (#1)




 
数据返回正常
 
 也走到这里边了，应该显示空布局的，然而并没有显示

**Comment by wushaoge** [comment]
vm记得用vmObserverMain这个

**Comment by jackandroid2016** [comment]
loading 是不是true?在哪里看
我就写了一个fragment

**Comment by jackandroid2016** [comment]
我试一下

**Comment by jackandroid2016** [comment]
可以了

**Comment by jackandroid2016** [comment]
空布局的时间还可以上拉加载，这个好像没处理

**Comment by wushaoge** [comment]
嗯 demo写的比较简单&nbsp; 可以在空布局的时候设置smartrefresh不能上拉加载，有个属性可以设置



---原始邮件---
发件人: "风..."<notifications@github.com&gt;
发送时间: 2020年10月3日(周六) 晚上11:30
收件人: "wushaoge/WsgMvvm"<WsgMvvm@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"wushaoge"<529500098@qq.com&gt;;
主题: Re: [wushaoge/WsgMvvm] 模仿homefragment 写了一个界面，显示空白 (#1)




 
空布局的时间还可以上拉加载，这个好像没处理

**Comment by jackandroid2016** [comment]
单fragment 没问题，我用了tablaout + fragment(fragment公用同一个)，又不显示布局了，用的vmObserverMain

**Comment by wushaoge** [comment]
> 单fragment 没问题，我用了tablaout + fragment(fragment公用同一个)，又不显示布局了，用的vmObserverMain

```
 open fun isShowLoading(): Boolean { return false }
```
不需要网络请求就可以显示的页面这个记得 return false，  return true适用于必须网络请求成功才可以显示的页面当然要配合vmObserverMain。页面有几个公共的状态你可以看一下。

**Comment by jackandroid2016** [comment]
需要网络请求显示

**Comment by jackandroid2016** [comment]
我在想会不会是因为公用fragment的问题

**Comment by wushaoge** [comment]
fragment需要，承载fragment的activity需要吗&nbsp; fragment和activity的状态都是分开的。可以加我QQ讨论，方便点529500098



---原始邮件---
发件人: "风..."<notifications@github.com&gt;
发送时间: 2020年10月4日(周日) 上午10:22
收件人: "wushaoge/WsgMvvm"<WsgMvvm@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"wushaoge"<529500098@qq.com&gt;;
主题: Re: [wushaoge/WsgMvvm] 模仿homefragment 写了一个界面，显示空白 (#1)




 
需要网络请求显示

**Comment by jackandroid2016** [comment]
recycleview 的 子控件点击事件没生效
