### ISSUE TITLE
设备重启后无法打开应用

### ISSUE THREAD

**Issue by is1988** [wushaoge/WsgMvvm#2]
<img width="1280" alt="截屏2021-01-22 下午4 13 45" src="https://user-images.githubusercontent.com/15359987/105466277-f34f2200-5cce-11eb-854e-7e27e35fb2f8.png">

手头目前没有测试机，用的mumu模拟器，每天来打开APP都会闪退，只能重新跑一遍代码，后来发现，只要我重启模拟器就会出现类似问题。

**报错如图，我想会不会是模拟器的问题。**

最后谢谢作者开源代码，写了好多年的Java了，如今想转kotlin，你这个很全面，学到了很多东西，但是一些高端的方法封装，有点看不懂，不知道有没有更容易入门的demo推荐。

**Comment by wushaoge** [comment]
图片打不开,应该是模拟器的问题，你可以用真机测一下，高阶方法的话多练练其实就能明白，demo除了mvvm封装那边稍微难理解点,其它都还好

**Comment by is1988** [comment]
这图还真看不到，我传到网盘了，如果大神有时间可以看一下。
链接: https://pan.baidu.com/s/1s1BUz-xKHuyoJuOuNOAkrQ 提取码: v367 
因为我其他kotlin的小demo没有闪退，就这个有问题。

**Comment by wushaoge** [comment]
MyApplication里面把DoraemonKit.install(instance)注释掉,可能模拟器debug模式下有问题

**Comment by is1988** [comment]
已解决，谢谢大佬
